services:
  kafka-ui:
    profiles: [tools]
    image: provectuslabs/kafka-ui:latest
    container_name: ${COMPOSE_PROJECT_NAME}-kafka-ui
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: testplatform-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - platform-network